import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";

import { Provider as ChakraProvider } from "./ChakraProvider";
import StoreProvider from "./StoreProvider";
import Header from "./components/Header";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movie Rating",
  description: "Generated by create next app",
};

const MOCK_SERVER = process.env.MOCK_SERVER;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let data = [];
  try {
    let res = await fetch(`${MOCK_SERVER}/movies`);
    data = await res.json();
  } catch (e) {
    console.log(e);
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider movies={data}>
          <ChakraProvider>
            <main className="sm:w-[1080px] w-full mx-auto">
              <Header />
              {children}
            </main>
          </ChakraProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
